after executing "clearing_deleting_files.py" this should be gone